(maven-build) Minor fix to correctly print vars.

diff --git a/headless_build/orcc_run_compilation b/headless_build/orcc_run_compilation
--- a/headless_build/orcc_run_compilation
+++ b/headless_build/orcc_run_compilation
@@ -74,9 +74,9 @@ $ECLIPSE_DIR/eclipse    -nosplash -consoleLog \
 
 rc=$?
 if [[ $rc -ne 0 ]] ; then
-  echo '$NETWORK compilation with $BACKEND backend failed'; exit $rc
+  echo "$NETWORK compilation with $BACKEND backend failed"; exit $rc
 else
-  echo '$NETWORK successfully compiled with $BACKEND backend';
+  echo "$NETWORK successfully compiled with $BACKEND backend";
 fi
 
 echo "***END*** $0 $(date -R)"
