(maven-build) Updating command-line scripts.

diff --git a/headless_build/orcc_eclipse_setup b/headless_build/orcc_eclipse_setup
--- a/headless_build/orcc_eclipse_setup
+++ b/headless_build/orcc_eclipse_setup
@@ -5,8 +5,8 @@ NBARGS=2
 function print_usage() {
     echo
     echo "Usage: $0 <eclipse_directory> <repository_url>"
-    echo "    <eclipse_directory>           The directory where Eclipse will be installed"
-    echo "    <repository_url>              The repository URL (e.g. http://orcc.sourceforge.net/eclipse/ or file:/user/local/path)"
+    echo "    <eclipse_directory>           Path to the directory where Eclipse will be installed"
+    echo "    <repository_url>              Repository URL (e.g. http://orcc.sourceforge.net/eclipse/ or file:/user/local/path)"
 }
 
 if [ $# -lt $NBARGS ]; then
@@ -14,14 +14,14 @@ if [ $# -lt $NBARGS ]; then
     exit $E_BADARGS
 fi
 
-# The Eclipse download url (if you want to change the mirror just select one from https://eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/R/eclipse-rcp-mars-R-linux-gtk-x86_64.tar.gz&format=xml )
-ECLIPSE_DOWNLOAD_URL="http://mirror.switch.ch/eclipse/technology/epp/downloads/release/mars/R/eclipse-rcp-mars-R-linux-gtk-x86_64.tar.gz"
-FEATURES="net.sf.orcc.feature.feature.group"
-
 # The eclipse directory (e.g. /home/scb/Development/test/eclipse )
 ECLIPSE_DIR=$1
 # The orcc eclipse plugins respository site (e.g. file:/home/scb/development/orcc/eclipse/plugins/net.sf.orcc.site/target/repository/)
 ORCC_REPO=$2
+
+# The Eclipse download url (if you want to change the mirror just select one from https://eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/R/eclipse-rcp-mars-R-linux-gtk-x86_64.tar.gz&format=xml )
+ECLIPSE_DOWNLOAD_URL="http://mirror.switch.ch/eclipse/technology/epp/downloads/release/mars/R/eclipse-rcp-mars-R-linux-gtk-x86_64.tar.gz"
+ORCC_FEATURES="net.sf.orcc.feature.feature.group"
 
 echo "***START*** $0 $(date -R)"
 
@@ -52,6 +52,12 @@ $ECLIPSE_DIR/eclipse   -nosplash -consoleLog \
                         -application org.eclipse.equinox.p2.director \
                         -repository $ORCC_REPO \
                         -followReferences \
-                        -installIU $FEATURES
+                        -installIU $ORCC_FEATURES
+rc=$?
+if [[ $rc -ne 0 ]] ; then
+  echo 'Eclipse setup with orcc plugin failed'; exit $rc
+else
+  echo 'Eclipse successfully setup with orcc plugin';
+fi
 
 echo "***END*** $0 $(date -R)"
diff --git a/headless_build/orcc_run_compilation b/headless_build/orcc_run_compilation
--- a/headless_build/orcc_run_compilation
+++ b/headless_build/orcc_run_compilation
@@ -1,80 +1,82 @@
 #!/bin/bash
+## Compile with a orcc backend
 
 NBARGS=6
 function print_usage() {
     echo
-    echo "Usage: $0 <working_directory> <projects_dir> <backend> <project> <top_network> <output_dir> [<additional_flags>]"
-    echo "    <working_directory>           Path to folder used to perform build & tests"
-    echo "    <projects_dir>                Folder containing CAL projects"
-    echo "    <backend>                     Identifier of the backend tu use (c, llvm, jade, tta, etc.)"
-    echo "    <project>                     The project containing application to build"
+    echo "Usage: $0 <eclipse_dir> <projects_dir> <backend> <project> <top_network> <output_dir> [<args> <eclipse_ws>]"
+    echo "    <eclipse_dir>           		Path to the directory where Eclipse is installed"
+    echo "    <projects_dir>                Path to the directory containing CAL projects"
+    echo "    <backend>                     Identifier of the backend to use (c, llvm, jade, tta, etc.)"
+    echo "    <project>                     Name of RVC-CAL project containing application to build"
     echo "    <top_network>                 Qualified name of the top network to build"
-    echo "    <output_dir>                  Folder where application will be built"
-    echo "    <additional_flags>            [Optional] Flags added to backend execution command line"
+    echo "    <output_dir>                  Path to the directory where output will be generated"
+    echo "    <args>                     	[Optional] Arguments/flags needed by backend execution command line"
+    echo "    <eclipse_ws>           		[Optional] Path to the directory where Eclipse workspace should be setup"
 }
-
-source $(dirname $0)/defines.sh
 
 if [ $# -lt $NBARGS ]; then
     print_usage
     exit $E_BADARGS
 fi
 
-[ ! -d "$2" ] && echo "Missing CAL projects folder" && print_usage && exit $E_BADARGS
+[ ! -d "$1" ] && echo "Missing eclipse directory" && print_usage && exit $E_BADARGS
+[ ! -d "$2" ] && echo "Missing CAL projects directory" && print_usage && exit $E_BADARGS
 [ -z "$3" ] && echo "Missing backend name" && print_usage && exit $E_BADARGS
 [ -z "$4" ] && echo "Missing project name" && print_usage && exit $E_BADARGS
 [ -z "$5" ] && echo "Missing top network qualified name" && print_usage && exit $E_BADARGS
-[ -z "$6" ] && echo "Missing output folder" && print_usage && exit $E_BADARGS
+[ -z "$6" ] && echo "Missing output directory" && print_usage && exit $E_BADARGS
 
-APPDIR=$2
+ECLIPSE_DIR=$1
+PROJECTS_DIR=$2
 BACKEND=$3
-PROJECT=$4
+PROJECT_NAME=$4
 NETWORK=$5
-OUTPUT=$6
-FLAGS=$7
+OUTPUT_DIR=$6
+ARGS=$7
+ECLIPSE_WS=${8:-"eclipse_workspace"}
 
 echo "***START*** $0 $(date -R)"
 
-[ ! -d "$OUTPUT" ] && mkdir -p $OUTPUT
+[ ! -d "$OUTPUT_DIR" ] && mkdir -p $OUTPUT_DIR
+[ ! -d "$ECLIPSE_WS" ] && mkdir -p $ECLIPSE_WS
 
-# This script does not manage separated workspace / cal applications folders
-# Hope this will be implemented in the future
-RUNWORKSPACE=$APPDIR
+RUNWORKSPACE=$ECLIPSE_WS
 
 rm -fr $RUNWORKSPACE/.metadata $RUNWORKSPACE/.JETEmitters
-rm -fr $APPDIR/**/bin
+rm -fr $RUNWORKSPACE/**/bin
 
 echo "Register Orcc projects in eclipse workspace"
-$ECLIPSERUN/eclipse     -nosplash -consoleLog \
+$ECLIPSE_DIR/eclipse    -nosplash -consoleLog \
                         -application net.sf.orcc.cal.workspaceSetup \
                         -data $RUNWORKSPACE \
-                        $APPDIR
+                        $PROJECTS_DIR
 
-# Frontend will generate IR only for used files. But all IR must be generated for jade and java backend
-if [ "$BACKEND" != "jade" ] && [ "$BACKEND" != "java" ]; then
-    FENETWORK=$NETWORK
-fi
-
-echo ""
-echo "Generate Orcc IR for $PROJECT and projects it depends on"
-$ECLIPSERUN/eclipse     -nosplash -consoleLog \
+echo "Generate Orcc IR for $PROJECT_NAME and projects it depends on"
+$ECLIPSE_DIR/eclipse    -nosplash -consoleLog \
                         -application net.sf.orcc.cal.cli \
                         -data $RUNWORKSPACE \
-                        $PROJECT \
-                        $FENETWORK \
-                        -vmargs -Xms40m -Xmx768m
-
-rm -fr $OUTPUT/*
-
-echo ""
-echo "Build application with $BACKEND backend"
-$ECLIPSERUN/eclipse     -nosplash -consoleLog \
-                        -application net.sf.orcc.backends.$BACKEND \
-                        -data $RUNWORKSPACE \
-                        -p $PROJECT \
-                        -o $OUTPUT \
-                        $FLAGS \
+                        $PROJECT_NAME \
                         $NETWORK \
                         -vmargs -Xms40m -Xmx768m
+
+rm -fr $OUTPUT_DIR/*
+
+echo "Build application with $BACKEND backend"
+$ECLIPSE_DIR/eclipse    -nosplash -consoleLog \
+                        -application net.sf.orcc.backends.$BACKEND \
+                        -data $RUNWORKSPACE \
+                        -p $PROJECT_NAME \
+                        -o $OUTPUT_DIR \
+                        $ARGS \
+                        $NETWORK \
+                        -vmargs -Xms40m -Xmx768m
+
+rc=$?
+if [[ $rc -ne 0 ]] ; then
+  echo '$NETWORK compilation with $BACKEND backend failed'; exit $rc
+else
+  echo '$NETWORK successfully compiled with $BACKEND backend';
+fi
 
 echo "***END*** $0 $(date -R)"
diff --git a/headless_build/orcc_run_simulation b/headless_build/orcc_run_simulation
--- a/headless_build/orcc_run_simulation
+++ b/headless_build/orcc_run_simulation
@@ -1,65 +1,68 @@
 #!/bin/bash
 
-NBARGS=5
+NBARGS=6
 function print_usage() {
     echo
-    echo "Usage: $0 <working_directory> <projects_dir> <project> <top_network> <input_sequence> [<reference_file>]"
-    echo "    <working_directory>           Path to folder used to perform build & tests"
-    echo "    <projects_dir>                Folder containing CAL projects"
-    echo "    <project>                     The project containing application to build"
+    echo "Usage: $0 <eclipse_directory> <projects_dir> <project> <top_network> <input_sequence> [<reference_file>]"
+    echo "    <eclipse_dir>           		Path to the directory where Eclipse is installed"
+    echo "    <projects_dir>                Path to the directory containing CAL projects"
+    echo "    <project>                     Name of RVC-CAL project containing application to build"
     echo "    <top_network>                 Qualified name of the top network to build"
+    echo "    <fifo_size>                 	Fifo size"
     echo "    <input_sequence>              Input file to pass to application"
     echo "    <reference_file>              [Optional] Reference file to use for errors checking"
 }
-
-source $(dirname $0)/defines.sh
 
 if [ $# -lt $NBARGS ]; then
     print_usage
     exit $E_BADARGS
 fi
 
-[ ! -s "$2" ] && echo "Missing CAL projects folder" && print_usage && exit $E_BADARGS
+[ ! -d "$1" ] && echo "Missing eclipse directory" && print_usage && exit $E_BADARGS
+[ ! -d "$2" ] && echo "Missing CAL projects directory" && print_usage && exit $E_BADARGS
 [ -z "$3" ] && echo "Missing project name" && print_usage && exit $E_BADARGS
 [ -z "$4" ] && echo "Missing top network qualified name" && print_usage && exit $E_BADARGS
-[ ! -s "$5" ] && echo "Missing input sequence" && print_usage && exit $E_BADARGS
-[ -f "$6" ] && REFOPTION="-r $6"
+[ -z "$5" ] && echo "Missing fifo size" && print_usage && exit $E_BADARGS
+[ ! -s "$6" ] && echo "Missing input sequence" && print_usage && exit $E_BADARGS
+[ -f "$7" ] && REFOPTION="-r $7"
 
-APPDIR=$2
-PROJECT=$3
+ECLIPSE_DIR=$1
+PROJECTS_DIR=$2
+PROJECT_NAME=$3
 NETWORK=$4
-INPUT=$5
+FIFO_SIZE=$5
+INPUT=$6
 
-# Split 2 test to perform a "short circuit evaluation"
-[ "$FIFOSIZE" -ge 2 ] 2>/dev/null && SETFIFO="-s $FIFOSIZE" && echo "Fifo size set to $FIFOSIZE"
+SETFIFO="-s $FIFO_SIZE" 
+echo "Fifo size set to $FIFO_SIZE"
 
 echo "***START*** $0 $(date -R)"
 
-RUNWORKSPACE=$APPDIR
+RUNWORKSPACE=$PROJECTS_DIR
 rm -fr $RUNWORKSPACE/.metadata $RUNWORKSPACE/.JETEmitters
 rm -fr $RUNWORKSPACE/**/bin
 
 echo "Register Orcc projects in eclipse workspace"
-$ECLIPSERUN/eclipse     -nosplash -consoleLog \
+$ECLIPSE_DIR/eclipse     -nosplash -consoleLog \
                         -application net.sf.orcc.cal.workspaceSetup \
                         -data $RUNWORKSPACE \
-                        $APPDIR
+                        $PROJECTS_DIR
 
-echo "Generate Orcc IR for $PROJECT and projects it depends on"
-$ECLIPSERUN/eclipse     -nosplash -consoleLog \
+echo "Generate Orcc IR for $PROJECT_NAME and projects it depends on"
+$ECLIPSE_DIR/eclipse     -nosplash -consoleLog \
                         -application net.sf.orcc.cal.cli \
                         -data $RUNWORKSPACE \
-                        $PROJECT \
+                        $PROJECT_NAME \
                         $NETWORK \
                         -vmargs -Xms40m -Xmx768m
 
 echo "Run simulation"
-$ECLIPSERUN/eclipse     -nosplash -consoleLog \
+$ECLIPSE_DIR/eclipse     -nosplash -consoleLog \
                         -application net.sf.orcc.simulators.cli \
                         -data $RUNWORKSPACE \
                         -n \
                         -i $INPUT \
-                        -p $PROJECT \
+                        -p $PROJECT_NAME \
                         $SETFIFO \
                         $REFOPTION \
                         $NETWORK \
diff --git a/headless_build/orcc_tests b/headless_build/orcc_tests
--- a/headless_build/orcc_tests
+++ b/headless_build/orcc_tests
@@ -3,21 +3,26 @@
 NBARGS=2
 function print_usage() {
     echo
-    echo "Usage: $0 <working_directory> <plugins_dir>"
-    echo "    <working_directory>           Path to folder used to perform build & tests"
-    echo "    <plugins_dir>                 Path to folder containing orcc plugins, in binary format (*.jar)"
+    echo "Usage: $0 <eclipse_directory> <plugins_dir>"
+    echo "    <eclipse_directory>           Path to the directory where Eclipse is installed"
+    echo "    <orcc_dir>                 	Path to the directory where orcc is cloned"
 }
-
-source $(dirname $0)/defines.sh
 
 if [ $# -lt $NBARGS ]; then
     print_usage
     exit $E_BADARGS
 fi
 
-[ ! -d "$2" ] && echo "Missing plugins directory" && print_usage && exit $E_BADARGS
+[ ! -d "$1" ] && echo "Missing eclipse directory" && print_usage && exit $E_BADARGS
+[ ! -d "$2" ] && echo "Missing orcc directory" && print_usage && exit $E_BADARGS
 
-JARPLUGINSDIR=$(readlink -f $2)
+ECLIPSE_DIR=$(readlink -f $1)
+ORCC_DIR=$(readlink -f $2)
+PLUGINS_DIR=$ORCC_DIR/eclipse/plugins/
+JARPLUGINS_DIR=$ORCC_DIR/eclipse/plugins/net.sf.orcc.site/target/repository
+
+SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+JGRAPHT_DIR=$SCRIPT_DIR/../lib/jgrapht-0.9.0
 
 mkdir -p junit-results
 resultsDir=$(readlink -f junit-results)
@@ -31,22 +36,22 @@ cat > $buildFile <<EOF
 			<formatter type="xml" />
 			<classpath>
 				<pathelement path="\${java.class.path}/"/>
-				<fileset dir="${ECLIPSEBUILD}/plugins">
+				<fileset dir="${ECLIPSE_DIR}/plugins">
 					<include name="org.junit_4*/junit.jar" />
 					<include name="*.jar" />
 				</fileset>
-				<fileset dir="${JARPLUGINSDIR}">
+				<fileset dir="${JARPLUGINS_DIR}">
 					<include name="*.jar" />
 				</fileset>
-				<fileset dir="${JGRAPHTPATH}">
+				<fileset dir="${JGRAPHT_DIR}">
 					<include name="*.jar" />
 				</fileset>
 			</classpath>
 			<batchtest fork="true" todir="${resultsDir}">
-				<fileset dir="$PLUGINSDIR/net.sf.orcc.cal.tests/src">
+				<fileset dir="$PLUGINS_DIR/net.sf.orcc.cal.tests/src">
 					<include name="net/sf/orcc/tests/main/*.java" />
 				</fileset>
-				<fileset dir="$PLUGINSDIR/net.sf.orcc.cal.tests/xtend-gen">
+				<fileset dir="$PLUGINS_DIR/net.sf.orcc.cal.tests/xtend-gen">
 					<include name="net/sf/orcc/tests/main/*.java" />
 				</fileset>
 			</batchtest>
